import { Component, OnInit } from '@angular/core';
import {
  FormGroup,
  FormControl,
  Validators,
  FormBuilder,
  AbstractControl,
  FormArray
} from '@angular/forms';
import { ApiService } from '../api.service';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.css']
})
export class FormComponent implements OnInit {
  adddetails: FormGroup;

  public submitform : number

  public areas = [
    'Adambakkam ',
    'Adyar ',
    'Alandur ',
    'Alwarpet ',
    'Alwarthirunagar ',
    'Ambattur ',
    'Aminjikarai ',
    'Anakaputhur ',
    'Anna Nagar ',
    'Annanur ',
    'Arumbakkam ',
    'Ashok Nagar ',
    'Avadi ',
    'Ayanavaram ',
    'Besant Nagar ',
    'Basin Bridge ',
    'Chepauk ',
    'Chetput ',
    'Chintadripet ',
    'Chitlapakkam ',
    'Choolai ',
    'Choolaimedu ',
    'Chrompet ',
    'Egmore ',
    'Ekkaduthangal ',
    'Ennore ',
    'Foreshore Estate ',
    'Fort St. George ',
    'George Town ',
    'Gopalapuram ',
    'Government Estate ',
    'Guindy ',
    'IIT Madras ',
    'Injambakkam ',
    'ICF ',
    'Iyyapanthangal ',
    'Jafferkhanpet ',
    'Karapakkam ',
    'Kattivakkam ',
    'Kazhipattur ',
    'K.K. Nagar ',
    'Keelkattalai ',
    'Kelambakkam ',
    'Kilpauk ',
    'Kodambakkam ',
    'Kodungaiyur ',
    'Kolathur ',
    'Korattur ',
    'Korukkupet ',
    'Kottivakkam ',
    'Kotturpuram ',
    'Kottur ',
    'Kovalam ',
    'Kovilambakkam ',
    'Koyambedu ',
    'Kundrathur ',
    'Madhavaram ',
    'Madhavaram Milk Colony ',
    'Madipakkam ',
    'Madambakkam ',
    'Maduravoyal ',
    'Manali ',
    'Manali New Town ',
    'Manapakkam ',
    'Mandaveli ',
    'Mangadu ',
    'Mannady ',
    'Mathur ',
    'Medavakkam ',
    'Meenambakkam ',
    'MGR Nagar ',
    'Minjur ',
    'Mogappair ',
    'MKB Nagar ',
    'Mount Road ',
    'Moolakadai ',
    'Moulivakkam ',
    'Mugalivakkam ',
    'Mudichur ',
    'Mylapore ',
    'Nandanam ',
    'Nanganallur ',
    'Navalur ',
    'Neelankarai ',
    'Nemilichery ',
    'Nesapakkam ',
    'Nolambur ',
    'Noombal ',
    'Nungambakkam ',
    'Otteri ',
    'Padi ',
    'Pakkam ',
    'Palavakkam ',
    'Pallavaram ',
    'Pallikaranai ',
    'Pammal ',
    'Park Town ',
    "Parry's Corner ",
    'Pattabiram ',
    'Pattaravakkam ',
    'Pazhavanthangal ',
    'Peerkankaranai ',
    'Perambur ',
    'Peravallur ',
    'Perumbakkam ',
    'Perungalathur ',
    'Perungudi ',
    'Pozhichalur ',
    'Poonamallee ',
    'Porur ',
    'Pudupet ',
    'Purasaiwalkam ',
    'Puthagaram ',
    'Puzhal ',
    'Puzhuthivakkam ',
    'Raj Bhavan ',
    'Ramavaram ',
    'Red Hills ',
    'Royapettah ',
    'Royapuram ',
    'Saidapet ',
    'Saligramam ',
    'Santhome ',
    'Sembakkam ',
    'Selaiyur ',
    'Shenoy Nagar ',
    'Sholavaram ',
    'Sholinganallur ',
    'Sithalapakkam ',
    'Sowcarpet ',
    'St.Thomas Mount ',
    'Tambaram ',
    'Teynampet ',
    'Tharamani ',
    'T. Nagar ',
    'Thirumangalam ',
    'Thirumullaivoyal ',
    'Thiruneermalai ',
    'Thiruninravur ',
    'Thiruvanmiyur ',
    'Tiruverkadu ',
    'Thiruvotriyur ',
    'Tirusulam ',
    'Tiruvallikeni ',
    'Tiruvallur ',
    'Tondiarpet ',
    'United India Colony ',
    'Vandalur ',
    'Vadapalani ',
    'Valasaravakkam ',
    'Vallalar Nagar ',
    'Vanagaram ',
    'Velachery ',
    'Villivakkam ',
    'Virugambakkam ',
    'Vyasarpadi ',
    'Washermanpet ',
    'West Mambalam'
  ];

  constructor(private fb: FormBuilder, private api: ApiService) {}

  ngOnInit() {
    this.adddetails = this.fb.group({
      name: new FormControl('', Validators.required),
      mobile: new FormControl('', [
        Validators.required,
        Validators.pattern('[789][0-9]{9}')
      ]),
      available_on: new FormControl('', Validators.required),
      area: new FormControl('', Validators.required)
    });
  }

  onSubmit() {
    this.submitform = 1;
    this.api
      .postdata('http://35.188.68.89/wacans/register', this.adddetails.value)
      .subscribe(data => {
        alert(data.message);
        window.location.href =
          'https://play.google.com/store/apps/details?id=com.wacans';
      });
  }
}
